[versions]
compose = "1.6.11"
kotlin = "2.0.0"

[libraries]
library-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
library-compose-ui-graphics = { module = "org.jetbrains.compose.ui:ui-graphics", version.ref = "compose" }

library-jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
library-jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

test-jUnit = { module = "junit:junit", version = "4.13.2" }

plugin-sonatype = { module = "dev.g000sha256:sonatype-maven-central", version = "0.0.4" }

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }